//! Falcon parameter definitions.

/// Supported Falcon logn for Falcon-512.
pub const FALCON512_LOGN: u32 = 9;

/// Supported Falcon logn for Falcon-1024.
pub const FALCON1024_LOGN: u32 = 10;

/// Default nonce length generated by the historical signing API.
pub const DEFAULT_NONCE_LEN: usize = 40;

/// Returns `true` when `logn` belongs to the public v1 API.
pub const fn is_public_logn(logn: u32) -> bool {
    matches!(logn, FALCON512_LOGN | FALCON1024_LOGN)
}
